version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pellwood-client
    hostname: pellwood-client
    restart: always
    env_file: .env
    environment:
      - APP_API=$APP_API
    ports:
      - "3001:3001"
    networks:
      - pellwoodClient

networks:
  pellwoodClient:
